name: Branch for release

on:
  schedule:
    - cron: "*/5 * * * *"
  # push:
  #   branches:
  #     - some-other-branch

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo $(date +'%Y-%m-%dT%H:%M:%S')
